spring.application.name=Gateway
spring.mongodb.uri=mongodb+srv://pulkit2489k_db_user:1234@cluster0.homkit.mongodb.net/?appName=Cluster0
spring.mongodb.database=WorkflowDef
server.error.include-message=always
server.error.include-binding-errors=always
